[package]
name = "async_demo"
version = "0.0.0"
edition = "2021"

[[bin]]
name = "sleepy"
path = "sleepy.rs"

[[bin]]
name = "busy"
path = "busy.rs"

[[bin]]
name = "join"
path = "join.rs"

[dependencies]
futures = "0.3.30"
