[package]
name = "async_demo"
version = "0.0.0"
edition = "2021"

[[bin]]
name = "regular"
path = "regular.rs"

[[bin]]
name = "threads"
path = "threads.rs"

[[bin]]
name = "rayon"
path = "rayon.rs"

[[bin]]
name = "tokio"
path = "tokio.rs"

[[bin]]
name = "sleep_mistake"
path = "sleep_mistake.rs"

[[bin]]
name = "join"
path = "join.rs"

[[bin]]
name = "busy"
path = "busy.rs"

[[bin]]
name = "sleepy"
path = "sleepy.rs"

[dependencies]
futures = "0.3.30"
rayon = "1.10.0"
tokio = { version = "1.39.2", features = ["full"] }
